name: Build and Deploy with Expo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Expo CLI and EAS CLI globally
      - name: Install Expo and EAS CLI
        run: npm install -g expo-cli eas-cli

      # Authenticate with Expo using EXPO_TOKEN
      - name: Set EXPO_TOKEN
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "Error: EXPO_TOKEN is not set. Please set it in your repository secrets."
            exit 1
          fi

      # Initialize EAS if not already configured
      - name: Initialize EAS project
        run: eas init --non-interactive || echo "EAS project already initialized."

      # Build the app with EAS
      - name: Build app
        run: eas build --platform all --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
